/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.mysql.cj.util.StringUtils;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextPane;
import model.CreadorModel;
import model.InitialController;
import model.MainClassModel;
import model.PeliculaModel;
import model.ProductoModel;
import model.SerieModel;

/**
 *
 * @author steve
 */
public class ProductoVista extends javax.swing.JFrame {

    /**
     * Creates new form ProductoVista
     */
    public ProductoVista() {
        initComponents();
        
        
    }
    private ProductoModel           productoReceived;
    private String                  button;
    private SerieModel              serie;
    private PeliculaModel           pelicula;
    private InitialController       initialController = new InitialController();
    private ArrayList<CreadorModel> creadores;
    private CreadorModel            creador;
    
    public void setProductoReceived(ProductoModel productoReceived, String button) {
        this.productoReceived = productoReceived;
        this.button = button;
    }
    private  boolean isNumeric(String cadena){
	try {
		Double.parseDouble(cadena);
		return true;
	} catch (NumberFormatException nfe){
                JOptionPane.showMessageDialog(null, "ingrese valores numericos");
		return false;
	}
   
    }
    private  boolean isNumericInt(String cadena){
	try {
		Integer.parseInt(cadena);
		return true;
	} catch (NumberFormatException nfe){
                JOptionPane.showMessageDialog(null, "Ingrese valores enteros");
		return false;
	}
   
    }
    private boolean checkNumeric(){
        try {
		Double.parseDouble(jTextCreadorEdad.getText());
                Double.parseDouble(jTextAnio.getText());
                Double.parseDouble(jTextRating.getText());
                Double.parseDouble(jTextDuracionTemporadas.getText());
		return true;
	} catch (NumberFormatException nfe){
                JOptionPane.showMessageDialog(null, "ingrese valores numericos");
                jTextCreadorEdad.setText("");
                jTextAnio.setText(""+pelicula.getAnio());
                jTextRating.setText(""+pelicula.getRating());
                jTextDuracionTemporadas.setText(""+pelicula.getDuracion());
		return false;
	}
    }
    private void checkJText(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButtonReturnVista = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButtonCreateUpgrade = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTexPaneResumenEpisodios = new javax.swing.JTextPane();
        jButtonDelete = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jTextEpisodios = new javax.swing.JTextField();
        jLabelResumenEpisodios = new javax.swing.JLabel();
        jLabelDuracionTemporadas = new javax.swing.JLabel();
        jTextDuracionTemporadas = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextRating = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextAnio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jLabelTipo = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jTextCreadorNacionalidad = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxSelectedCreador = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jTextCreadorEdad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextCreadorNombre = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1012, 640));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(49, 27, 146));

        jPanel3.setBackground(new java.awt.Color(0, 0, 99));

        jButtonReturnVista.setBackground(new java.awt.Color(0, 0, 99));
        jButtonReturnVista.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReturnVista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/returnIcon.png"))); // NOI18N
        jButtonReturnVista.setText("Volver");
        jButtonReturnVista.setBorder(null);
        jButtonReturnVista.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonReturnVista.setMargin(new java.awt.Insets(2, 1, 2, 1));
        jButtonReturnVista.setPreferredSize(new java.awt.Dimension(97, 25));
        jButtonReturnVista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReturnVistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButtonReturnVista, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 942, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonReturnVista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel1.setFont(new java.awt.Font("Papyrus", 3, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MisionTicFlix");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(103, 70, 195));

        jButtonCreateUpgrade.setBackground(new java.awt.Color(0, 0, 99));
        jButtonCreateUpgrade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonCreateUpgrade.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCreateUpgrade.setText("ActuaLizar");
        jButtonCreateUpgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateUpgradeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCreateUpgrade, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jButtonCreateUpgrade, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        jTexPaneResumenEpisodios.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTexPaneResumenEpisodios.setToolTipText("");
        jScrollPane2.setViewportView(jTexPaneResumenEpisodios);

        jButtonDelete.setBackground(new java.awt.Color(0, 0, 99));
        jButtonDelete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonDelete.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDelete.setText("Eliminar producto");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 122, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
        );

        jTextEpisodios.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextEpisodios.setText("jTextField2");

        jLabelResumenEpisodios.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelResumenEpisodios.setText("Reumen:");

        jLabelDuracionTemporadas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelDuracionTemporadas.setText("Temporadas:");

        jTextDuracionTemporadas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextDuracionTemporadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDuracionTemporadasActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Rating:");

        jTextRating.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextRating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextRatingActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Año:");

        jTextAnio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextAnio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextAnioKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nombre:");

        jTextNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabelTipo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTipo.setText("Tipo");

        jComboBoxTipo.setBackground(new java.awt.Color(0, 0, 99));
        jComboBoxTipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxTipo.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pelicula", "Serie" }));
        jComboBoxTipo.setBorder(null);
        jComboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoActionPerformed(evt);
            }
        });

        jTextCreadorNacionalidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Nacionalidad:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Creador");

        jComboBoxSelectedCreador.setBackground(new java.awt.Color(0, 0, 99));
        jComboBoxSelectedCreador.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxSelectedCreador.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxSelectedCreador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nuevo Creador" }));
        jComboBoxSelectedCreador.setBorder(null);
        jComboBoxSelectedCreador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSelectedCreadorActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Edad:");

        jTextCreadorEdad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextCreadorEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCreadorEdadActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Nombre:");

        jTextCreadorNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 73, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonDelete)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelTipo)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelDuracionTemporadas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextDuracionTemporadas, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextRating, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelResumenEpisodios)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextEpisodios, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextCreadorEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextCreadorNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jComboBoxSelectedCreador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextCreadorNombre)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))))
                    .addComponent(jScrollPane2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTipo)
                            .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDuracionTemporadas)
                            .addComponent(jTextDuracionTemporadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelResumenEpisodios, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextEpisodios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBoxSelectedCreador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextCreadorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextCreadorNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextCreadorEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addComponent(jButtonDelete)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCreateUpgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateUpgradeActionPerformed
        // TODO add your handling code here:
        int id = -1;
        if(!(productoReceived == null)){
            id   = productoReceived.getId(); 
        }   
        if(!(jTextNombre.getText().isEmpty()) && !(jTextCreadorNombre.getText().isEmpty()) && checkNumeric()){

            String        nombre   = jTextNombre.getText(); 
            int           anio     = (int)Double.parseDouble(jTextAnio.getText());
            double        rating   = Double.parseDouble(jTextRating.getText());
            
            CreadorModel  creador  = new CreadorModel(jComboBoxSelectedCreador.getSelectedIndex()-1>0 ? creadores.get(jComboBoxSelectedCreador.getSelectedIndex()-1).getId():-1,
                    jTextCreadorNombre.getText(), jTextCreadorNacionalidad.getText(), (int)Double.parseDouble(jTextCreadorEdad.getText()));
            String        tipo     = (String)jComboBoxTipo.getSelectedItem();
            int           durTemp  = (int)Double.parseDouble(jTextDuracionTemporadas.getText());
            if(jComboBoxTipo.getSelectedIndex() == 1){ //1 Seriie 0 Pelicula
                int episodios = (int)Double.parseDouble(jTextEpisodios.getText());
            
                SerieModel newSerie = new SerieModel(id, nombre, anio, rating, durTemp, creador, episodios, tipo);
                
                initialController.setSerieDAO(newSerie);
            }else{
                String resumen = jTexPaneResumenEpisodios.getText();
                PeliculaModel newPelicula = new PeliculaModel(id, nombre, anio, rating, durTemp, creador, resumen, tipo);
                initialController.setPeliculaDAO(newPelicula);
            //  PeliculaModel newPelicula = new PeliculaModel();
            }
            MainClassModel.setVista();
        }
        
    }//GEN-LAST:event_jButtonCreateUpgradeActionPerformed

    private void jButtonReturnVistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReturnVistaActionPerformed
        // TODO add your handling code here:
        MainClassModel.setVista();
    }//GEN-LAST:event_jButtonReturnVistaActionPerformed
    
       
    
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
       creadores = initialController.getFilteredCreadorDAO("");
       jComboBoxSelectedCreador.removeAllItems();
       jComboBoxSelectedCreador.addItem("Nuevo Creador");
       for(int i=0; i<creadores.size(); i++){
           
           jComboBoxSelectedCreador.addItem(creadores.get(i).getNombre());
       }
       
       if(button.equals("Open")){
           
           jComboBoxTipo.setVisible(false);
           creador = productoReceived.getCreador();
           jComboBoxSelectedCreador.setSelectedIndex(creador.getId());
           /*parametros editables false en crador
           jTextCreadorEdad.setEditable(false);
           jTextCreadorNombre.setEditable(false);
           jTextCreadorNacionalidad.setEditable(false);
           */
           
           jButtonCreateUpgrade.setText("Actualizar");
           //set creador
           jTextCreadorNombre.setText(creador.getNombre());;
           jTextCreadorEdad.setText(""+creador.getEdad());
           jTextCreadorNacionalidad.setText(creador.getNacionalidad());
           //set producto
            if(productoReceived.getTipo().equals("Serie")){
                jTexPaneResumenEpisodios.setVisible(false);
                jTextEpisodios.setVisible(true);
                
                jComboBoxTipo.setSelectedIndex(1);
                jLabelTipo.setText("SERIE");
                jLabelDuracionTemporadas.setText("Temporadas:");
                jLabelResumenEpisodios.setText("Episodios:");
                
                
                this.serie = initialController.getSerie(productoReceived);
                
                jTextNombre.setText(serie.getNombre());
                jTextAnio.setText(""+serie.getAnio());
                jTextRating.setText(""+serie.getRating());
                jTextDuracionTemporadas.setText(""+serie.getTemporadas());
                jTexPaneResumenEpisodios.setText("");
                
                jTextEpisodios.setText(""+serie.getEpisodios());
                
                
            }else{
                
                jComboBoxTipo.setSelectedIndex(0);
                jLabelTipo.setText("PELICULA");
                jLabelDuracionTemporadas.setText("Duración:");
                jLabelResumenEpisodios.setText("Resumen:");
                
                this.pelicula = initialController.getPelicula(productoReceived);
                jTextEpisodios.setVisible(false);
                jTexPaneResumenEpisodios.setVisible(true);
                
                jTextNombre.setText(pelicula.getNombre());
                jTextAnio.setText(""+pelicula.getAnio());
                jTextRating.setText(""+pelicula.getRating());
                jTextDuracionTemporadas.setText(""+pelicula.getDuracion());
                jTextEpisodios.setText("");
                
                jTexPaneResumenEpisodios.setText(""+pelicula.getResumen());
                
                
            }
       }else{
           jComboBoxSelectedCreador.setSelectedIndex(0);
           jComboBoxTipo.setSelectedIndex(0);
           jComboBoxTipo.setVisible(true);
           jTextEpisodios.setVisible(false);
                jTexPaneResumenEpisodios.setVisible(true);
           //jComboBoxTipo.setEditable(true);
           jButtonCreateUpgrade.setText("Crear");
           jButtonDelete.setVisible(false);
           jLabelTipo.setText("Seleccione Tipo");
           
           //set creador
           jTextCreadorNombre.setText("");;
           jTextCreadorEdad.setText("");
           jTextCreadorNacionalidad.setText("");
           jComboBoxSelectedCreador.setSelectedIndex(0);
                jLabelDuracionTemporadas.setText("");
                jLabelResumenEpisodios.setText("");
                
                jLabelDuracionTemporadas.setText("Duración:");
                jLabelResumenEpisodios.setText("Resumen:");
                
                jTextNombre.setText("");
                jTextAnio.setText("");
                jTextRating.setText("");
                jTextDuracionTemporadas.setText("");
                 jTextEpisodios.setText("");
                
                
                jTexPaneResumenEpisodios.setText("");
           
       
       }       
    }//GEN-LAST:event_formWindowActivated

    private void jTextAnioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAnioKeyReleased
        // TODO add your handling code here:
        String str = jTextAnio.getText();
        if(!isNumericInt(str)){
            jTextAnio.setText(str.substring(0, str.length()-2).replaceAll(" ",""));
        }
    }//GEN-LAST:event_jTextAnioKeyReleased

    private void jTextRatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextRatingActionPerformed
        // TODO add your handling code here:
        String str = jTextRating.getText();
        if(!isNumeric(str)){
            jTextRating.setText(str.substring(0, str.length()-1).replaceAll(" ",""));
            
        }
    }//GEN-LAST:event_jTextRatingActionPerformed

    private void jTextDuracionTemporadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDuracionTemporadasActionPerformed
        // TODO add your handling code here:
        String str = jTextDuracionTemporadas.getText();
        if(!isNumericInt(str)){
            jTextDuracionTemporadas.setText(str.substring(0, str.length()-2).replaceAll(" ",""));
        }
    }//GEN-LAST:event_jTextDuracionTemporadasActionPerformed

    private void jTextCreadorEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCreadorEdadActionPerformed
        // TODO add your handling code here:
        String str = jTextCreadorEdad.getText();
        if(!isNumericInt(str)){
            jTextCreadorEdad.setText(str.substring(0, str.length()-2).replaceAll(" ",""));
        }
    }//GEN-LAST:event_jTextCreadorEdadActionPerformed

    private void jComboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoActionPerformed
        // TODO add your handling code here:
        
        if(jComboBoxTipo.getSelectedIndex() == 1){//1 serie 0= peliculas
            jLabelDuracionTemporadas.setText("Temporadas:");
                jLabelResumenEpisodios.setText("Episodios:");
                jTextEpisodios.setVisible(true);
                jTexPaneResumenEpisodios.setVisible(false);
                jScrollPane2.setVisible(false);
        }else{
            jLabelDuracionTemporadas.setText("Duración:");
                
                jLabelResumenEpisodios.setText("Resumen:");
                jTextEpisodios.setVisible(false);
                jTexPaneResumenEpisodios.setVisible(true);
                 jScrollPane2.setVisible(true);
        }
    }//GEN-LAST:event_jComboBoxTipoActionPerformed

    private void jComboBoxSelectedCreadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSelectedCreadorActionPerformed
        // TODO add your handling code here:
        //System.out.println(jComboBoxSelectedCreador.getSelectedIndex()+ "  seleciono "+
              //  jComboBoxSelectedCreador.getSelectedItem()+" corresponde "+creadores.get(jComboBoxSelectedCreador.getSelectedIndex()-1).getNombre());
       if(jComboBoxSelectedCreador.getSelectedIndex() > 0){
           
           jTextCreadorNombre.setText(creadores.get(jComboBoxSelectedCreador.getSelectedIndex()-1).getNombre());
           jTextCreadorEdad.setText(""+creadores.get(jComboBoxSelectedCreador.getSelectedIndex()-1).getEdad());
           jTextCreadorNacionalidad.setText(creadores.get(jComboBoxSelectedCreador.getSelectedIndex()-1).getNacionalidad());
        }else{
           jTextCreadorNombre.setText("");
           jTextCreadorEdad.setText("");
           jTextCreadorNacionalidad.setText("");  
       }
       
        
    }//GEN-LAST:event_jComboBoxSelectedCreadorActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
       
            int resp = JOptionPane.showConfirmDialog(null, "Está seguro que desea eliminar el registro",
                "", JOptionPane.YES_NO_OPTION,
                JOptionPane.INFORMATION_MESSAGE);
            if(resp == 0){
                initialController.deleteProducto(productoReceived);
                MainClassModel.setVista();
            }
        
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductoVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCreateUpgrade;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonReturnVista;
    private javax.swing.JComboBox<String> jComboBoxSelectedCreador;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDuracionTemporadas;
    private javax.swing.JLabel jLabelResumenEpisodios;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTexPaneResumenEpisodios;
    private javax.swing.JTextField jTextAnio;
    private javax.swing.JTextField jTextCreadorEdad;
    private javax.swing.JTextField jTextCreadorNacionalidad;
    private javax.swing.JTextField jTextCreadorNombre;
    private javax.swing.JTextField jTextDuracionTemporadas;
    private javax.swing.JTextField jTextEpisodios;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextRating;
    // End of variables declaration//GEN-END:variables
}
